---
title: "STAT545A Individual Mini Data Analysis-Milestone 3"
author: "Sara Kowalski"
date: "October 19, 2021"
output: github_document
---



## Table of Contents
1. Introduction

2. Load packages
    + 2.1 Load **datateachr** and **tidyverse**
    + 2.2 My research questions
    
3. Task 1: Process and summarize *vancouver_trees*
    + 3.1 My 4 research questions
    + 3.2 Summarizing and graphing 
        + 3.2.1 Question 1
            + 3.2.1.1 Summarizing
            + 3.2.1.2 Graphing
        + 3.2.2 Question 2
            + 3.2.2.1 Summarizing
            + 3.2.2.2 Graphing
        + 3.2.3 Question 3
            + 3.2.3.1 Summarizing
            + 3.2.3.2 Graphing
        + 3.2.4 Question 4
            + 3.2.4.1 Summarizing
            + 3.2.4.2 Graphing
    + 3.3 Reflect on results 
    
4. Task 2: Tidy *vancouver_trees* dataset
    + 4.1 Is *vancouver_trees* tidy? 
    + 4.2 untidy, then tidy back *vancouver_trees*
    + 4.3 Choose 2 research questions
    + 4.4. Choose a version of *vancouver_trees*


## 1  Introduction
Hello! The following document contains the work required to complete Milestone 3 of the Mini Data Analysis Project in STAT545A.  

Much of the inspiration for this script comes from [Heads or Tails](https://www.kaggle.com/headsortails/tidy-titarnic) and from the [instructions](https://stat545.stat.ubc.ca/mini-project/mini-project-3/) provided for the project.

## 2  Load Packages 
### 2.1 Load **datateachr** and **tidyverse**

```{r}
## Load dataset package - datateachr
library(datateachr)

## Load tidyverse - a collection of R packages used for data analysis
library(tidyverse) 
```

### 2.2 My Research Questions

1. Question 1:
What is the distribution for tree species (from a specified genus (e.g. Ulmus)) within Vancouver neighbourhoods? Are certain tree species favored over others in specific neighbourhoods? 

2. Question 2:
Within each genus, what is the distribution of the diameter of the trees for each species? Which species have a wider diameter distribution and which ones have a more narrow distribution?